//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shopping_Center
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ShoppingCenterEntities : DbContext
    {
        public ShoppingCenterEntities()
            : base("name=ShoppingCenterEntities")
        {
        }

        private static ShoppingCenterEntities _context;
        public static ShoppingCenterEntities GetContext()
        {
            if (_context == null)
                _context = new ShoppingCenterEntities();
            return _context;
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Emplooyes> Emplooyes { get; set; }
        public virtual DbSet<Pavilions> Pavilions { get; set; }
        public virtual DbSet<Rents> Rents { get; set; }
        public virtual DbSet<Shopping_centers> Shopping_centers { get; set; }
        public virtual DbSet<Renters> Renters { get; set; }
    }
}
