//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shopping_Center
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rents
    {
        public int id_rent { get; set; }
        public string Number_pavilion { get; set; }
        public int id_shopping_center { get; set; }
        public int id_renter { get; set; }
        public int id_emplooye { get; set; }
        public string Status { get; set; }
        public System.DateTime Begin_rent { get; set; }
        public System.DateTime Ending_rent { get; set; }
    
        public virtual Emplooyes Emplooyes { get; set; }
        public virtual Pavilions Pavilions { get; set; }
        public virtual Renters Renters { get; set; }
    }
}
